#!/bin/bash
#SBATCH -A desi
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH -o ./slurm/log/job_array_test%j.out
#SBATCH -n 1
#SBATCH --time 24:00:00
#SBATCH --mail-type=BEGIN,ENd,FAIl
#SBATCH --mail-user=jayashreeb@phys.ksu.edu
# load packages
# conda activate halo
export HDF5_USE_FILE_LOCKING=FALSE

# run
#srun -n 1 -c 64 python all_bispectrum_mcmc.py --index $SLURM_ARRAY_TASK_ID
srun -n 1 -c 64 python bispectrum_mcmc.py